apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wot-blitz-statistics-mongo
  name: wot-blitz-statistics-pro-app-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wot-blitz-statistics-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wot-blitz-statistics-mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_INITDB_ROOT_USERNAME
        image: mongo
        imagePullPolicy: ""
        name: wot-blitz-statistics-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: blitz-mongodblvolume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: blitz-mongodblvolume
        persistentVolumeClaim:
          claimName: blitz-mongodblvolume
status: {}
