apiVersion: v1
kind: Service
metadata:
  labels:
    app: wot-blitz-statistics-mongo
  name: wot-blitz-statistics-pro-app-mongo-service
spec:
  ports:
  - name: "27027"
    port: 27027
    targetPort: 27017
  selector:
    app: wot-blitz-statistics-mongo
  type: LoadBalancer

