apiVersion: v1
kind: Service
metadata:
  labels:
    app: wot-blitz-statistics-web
  name: wot-blitz-statistics-pro-app-web-service
spec:
  selector:
    app: wot-blitz-statistics-web
  type: LoadBalancer
  ports:
  - name: "8040"
    port: 8040
    targetPort: 80